name: Deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: WooCommerce-Order         # 🔁 Thay bằng tên App Service của bạn
  AZURE_WEBAPP_PACKAGE_PATH: '.'            # 🔁 Đặt '.' nếu dự án ở thư mục gốc, hoặc './frontend' nếu trong thư mục con
  NODE_VERSION: '20.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Verify package-lock.json
        run: |
          if [ ! -f "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package-lock.json" ]; then
            echo "❌ package-lock.json not found!"
            exit 1
          fi

      - name: Install dependencies, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: none

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
