name: Build and Upload Artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'false'  # hoặc bỏ dòng này cũng được

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist
          include-hidden-files: true
